### ISSUE TITLE
Project ERROR: Could not find feature stack-protector-strong

### ISSUE THREAD

**Issue by Vistaus** [CrimsonAS/gtkplatform#20]
I'm trying to build from the latest git master but make ends on the error Project ERROR: Could not find feature stack-protector-strong

OS: Solus (Linux)
Qt version: 5.9.1 (all possible Qt devel packages are installed AFAIK since I'm also compiling other Qt software)

Am I missing something?

**Comment by rburchell** [comment]
No, you aren't. I'm aware of the problem (seems to affect only 5.9 and possibly upwards), but not yet sure of a solution. Thanks for filing an issue.

For reference, here's as far as I've gotten so far:

> It seems like the qtConfig function in qtbase’s prf files isn’t quite working right. If it’s patched to not error, but return false, then it seems to work fine. Help to figure out the real underlying cause would be welcome.

**Comment by rburchell** [comment]
cc @sirspudd, too.

**Comment by rburchell** [comment]
Looking at qmake -d -d -d on this versus an internal plugin, it seems like qmodule.pri isn't being used. It seems this is pulled in by QMAKE_INTERNAL_INCLUDED_FILES. Perhaps this is the real problem.

Can you try adding:

> load(qt_build_config)

... to gtkplatform/.qmake.conf (currently an empty file), and see if that has any impact?

**Comment by sirspudd** [comment]
That does the trick for me locally : D

**Comment by rburchell** [comment]
Thanks!

**Comment by Vistaus** [comment]
Thanks fot he quick fixin'! I can confirm that it's fixed now! :-)
