### ISSUE TITLE
Binary compatibility

### ISSUE THREAD

**Issue by mdrost** [CrimsonAS/gtkplatform#21]
For future binary compatibility you should consider using [d-pointer](http://wiki.qt.io/D-Pointer).

**Comment by rburchell** [comment]
I'm aware of the technique (I often work on Qt in my spare time). However, there is explicitly [no compatibility promises](https://doc.qt.io/qt-5/qpa.html) on gtkplatform, or on the QPA API it uses. It must be rebuilt whenever its dependencies are rebuilt.
