### ISSUE TITLE
Citra only gets a GL 3.0 context on GDK_BACKEND=wayland

### ISSUE THREAD

**Issue by linkmauve** [CrimsonAS/gtkplatform#24]
Citra asks for a core 3.3 context, and gets a 3.0 context instead.

See the context creation code here: https://github.com/citra-emu/citra/blob/master/src/citra_qt/bootmanager.cpp#L264

**Comment by rburchell** [comment]
Thanks for the report. Is there some kind of a way I can test this easily? I am not at all involved in emulation.

**Comment by linkmauve** [comment]
You can use any homebrew with Citra, most of them are free software, such as this one (which includes a pre-built binary): https://smealum.github.io/3dscraft/

Download it, unzip it, build Citra, then run `citra-qt 3ds/3dscraft/3dscraft.3dsx`.

**Comment by rburchell** [comment]
Thanks, that worked. @special, any ideas?

```
[W] default: QGtkOpenGLContext::QGtkOpenGLContext:85 - QSurfaceFormat(version 3.3, options QFlags(), depthBufferSize 1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 1, samples -1, swapBehavior 2, swapInterval 0, profile  1)
[   0.015436] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:488: GL_VERSION: 3.0 Mesa 17.1.7
[   0.015473] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:489: GL_VENDOR: Intel Open Source Technology Center
[   0.015477] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:490: GL_RENDERER: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
[   0.015495] Render <Error> video_core/video_core.cpp:Init:35: initialization failed !
[   0.015499] Core <Critical> core/core.cpp:Load:98: Failed to initialize system (Error 9)!
```

**Comment by special** [comment]
Well, turns out we're ignoring the surface format's version entirely for wayland contexts. So uh, that's why.

Will get this fixed later today.
