### ISSUE TITLE
Style plugin?

### ISSUE THREAD

**Issue by gnidorah** [CrimsonAS/gtkplatform#25]
Does this plugin also acts as style plugin (e.g. QGtkStyle)? I.e. will Qt programs be able to use GTK 3.x CSS theme? I need a replacement for QGtkStyle with GTK3 themes support. Sure platform additions are great benefit (matching fonts, behavior etc)

**Comment by rburchell** [comment]
No. I use the Adwaita style plugin which looks pretty good under GNOME.
