### ISSUE TITLE
File dialog filter name with parentheses cut at wrong position

### ISSUE THREAD

**Issue by jspitz** [CrimsonAS/gtkplatform#37]
I am copying this report from https://github.com/FedoraQt/QGnomePlatform/issues/35, since this seems to be the more active repo. I apologize if this is the wrong tracker (if so, I'd appreciate if you could point me to the right place).

In [qgtk3dialoghelpers.cpp#L449](https://github.com/CrimsonAS/gtkplatform/blob/5e0ab4b9869732a817f85db68a1f19293bac4ca0/src/platform-plugin/qgtk3dialoghelpers.cpp#L449), the filter name is stripped off as follows:
`const QString name = filter.left(filter.indexOf(QLatin1Char('(')));`

This blindly strips off all strings at parentheses, notwithstanding whether these parentheses are part of the name (as in "My File Format (Version 2)") or, as is the intended case, hold the suffixes. So "My File Format (Version 2) (*.mff)" is displayed as "My File Format" rather than "My File Format (Version 2)". This is a major usability problem with apps proposing multiple versions of a format to select from.

I suggest that you use the regexp from `QPlatformFileDialogHelper` instead, as in (untested):
```
QRegExp rx("^(.*)\\(([a-zA-Z0-9_.,*? +;#\\-\\[\\]@\\{\\}/!<>\\$%&=^~:\\|]*)\\)$");

foreach (const QString &filter, filters) {
        GtkFileFilter *gtkFilter = gtk_file_filter_new();
        QString name = filter
        int i = rx.indexIn(filter);
        if (i >= 0)
            name = regexp.cap(1);
        const QStringList extensions = cleanFilterList(filter);

        gtk_file_filter_set_name(gtkFilter, name.isEmpty() ? extensions.join(QStringLiteral(", ")).toUtf8() : name.toUtf8());
        foreach (const QString &ext, extensions)
            gtk_file_filter_add_pattern(gtkFilter, ext.toUtf8());

        gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtkDialog), gtkFilter);

        _filters.insert(filter, gtkFilter);
        _filterNames.insert(gtkFilter, filter);
}
```
A simpler solution, but probably not as accurate, would be
`const QString name = filter.left(filter.lastIndexOf(QLatin1Char('(')));`

**Comment by jspitz** [comment]
As a real world example, here is a snippet from the export file dialog filter menu of [LyX](https://www.lyx.org) when using the GTK platform Qt theme. As you see, it is impossible to select the correct PDF output format for instance (they are called "PDF (pdflatex)", "PDF (XeTeX)", "PDF (ps2pdf)" etc). Same applies to other export variants.
![bildschirmfoto von 2018-04-29 15-16-09](https://user-images.githubusercontent.com/4538783/39407082-fdf46a02-4bc0-11e8-85d3-1c12d723065b.png)

**Comment by rburchell** [comment]
This looks valid. I'll try take a look into getting a fix in when I get some time. If you can give me a short walkthrough on how I can easily get to that menu in LyX (as I don't know of it) to help verify the behaviour, that would be great.

**Comment by jspitz** [comment]
Thank you. As to the recipe:
1. Get and install LyX (https://www.lyx.org/Download)
2. Start LyX. There should be a welcoming document when you lauch the app for the first time. If not, just open any from the Help menu
3. Go to File >  Export > Export As...

In the file dialog, you have the mentioned filter combo (bottom right) 

Please let me know if you need more info.

**Comment by jspitz** [comment]
Do you need more info?

**Comment by rburchell** [comment]
No, this sounds good. I just haven't got time to fix this now.

**Comment by jspitz** [comment]
Still no time? The bug is really pretty annoying.

**Comment by rburchell** [comment]
[this is a mass update]

This is polite notice that gtkplatform is effectively end of life. Due to this, I've decided to archive the project.

I (and I think, the other contributors) have not been using it in quite some time, and I don't see that situation changing any time soon. In addition, none of us really have the time that it takes to do what it takes to keep the lights on, and this situation is going to get a lot harder soon with the impending arrival of Qt 6 and gtk 4 on the horizon.

Should anyone wish to take it over, you have my blessing to do so :)
