### ISSUE TITLE
DPI scaling is being applied twice

### ISSUE THREAD

**Issue by actionless** [CrimsonAS/gtkplatform#38]
On the screenshot you can see what menubar have normal 2x scaling but the rest is scaled 4x:

![2018-05-08--1525797136_1649x1063_scrot](https://user-images.githubusercontent.com/1655669/39770051-3de05372-52ee-11e8-9b55-3f852e949d35.png)

setting `GDK_SCALE=1` fixes the controls/font but makes the menubar and its menus unscaled (1x):

![2018-05-08--1525797227_1638x1056_scrot](https://user-images.githubusercontent.com/1655669/39770091-5ac92bbc-52ee-11e8-9008-2686253d2669.png)

**Comment by rburchell** [comment]
Unfortunately, I'm not able to reproduce this with gtk3-3.22 under either x11 or wayland using GNOME Shell. If you are able to find the cause (or better still, find a fix), that would be great.

Please make sure you are running at least gtkplatform 0.2.1, as there were some known DPI bugs prior to that (see b71b2c4f2a28f3bc2afc16fdd4b433d034da7ab8 and d491c37641545d1c68ea86d18586697c4783670e).

**Comment by actionless** [comment]
i am sure i am running the latest git version

that's quite a weird behavior to close a bug report instead of asking for the clarifications on how to reproduce the problem...

good luck on a project
