### ISSUE TITLE
GTK+3 theme is not applied

### ISSUE THREAD

**Issue by actionless** [CrimsonAS/gtkplatform#39]
theme is set in both `~/.config/gtk-3.0/settings.ini` and in x settings daemon (and so it works as expected in all the gtk3 apps, firefox and chrom*) but when running Qt5 apps via `gtkplatform` apps always end up with default Adwaita theme.

**Comment by actionless** [comment]
btw theme got applied to the menubar and menus

**Comment by rburchell** [comment]
The [adwaita-qt theme plugin](https://github.com/FedoraQt/adwaita-qt/blob/master/style/adwaitastyle.cpp) which gtkplatform relies on for the appearance of things other than menus would likely be a better place to look/file this - I'm not sure it supports custom themes offhand.

**Comment by actionless** [comment]
after roughly reading it seems it's sorta hardcoded to adwaita theme

and also i don't even see gtk in deps: https://github.com/FedoraQt/adwaita-qt/blob/master/CMakeLists.txt

**Comment by rburchell** [comment]
That doesn't surprise me much. gtk removed their theme API a number of releases ago, making it very difficult to match its theming behaviour. There is GtkStyleContext, but using that is not trivial (and neither is QStyle the easiest thing to use).

**Comment by actionless** [comment]
I was implementing basic gtk+3 support in awesome wm

Basically the problem is undocumented stylecontext:
https://gitlab.gnome.org/GNOME/gtk/issues/79

But it seems they don’t wanna fix it because of some alternatively smart
people on high positions in gnome design team..,
