### ISSUE TITLE
Locally integrated menus in headerbar

### ISSUE THREAD

**Issue by ripefig** [CrimsonAS/gtkplatform#47]
Is there a plan to make it possible to transfer the application menubars to the headerbar? This is the general idea (exact implementation may differ, obviously)

![image](https://user-images.githubusercontent.com/45201036/54490894-3702c480-48cb-11e9-95ac-9016aa9ba771.png)

Just wondering what could be done with the headerbars. Is moving some toolbars to the headerbar a possibility?

**Comment by rburchell** [comment]
If that's what gtk chooses to do with menus, then yes. Otherwise, no. This project is not implementing any new UI, it's just using what is already available.

**Comment by ripefig** [comment]
But what do you use the hearderbar for? QT apps have no concept of "headerbar". A toolbar maybe? @rburchell
